services:
  web:
    build:
      context: .
    volumes:
      - invoices_media:/app/staticfiles
    expose:
      - 8000

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web # Wait until web service is ready
    volumes:
      - invoices_media:/app/staticfiles
      - /etc/ssl/certs:/etc/nginx/ssl
      - /etc/ssl/private:/etc/nginx/ssl/private

volumes:
  invoices_media: