name: Deploy

on:
  push:
    branches: [develop]

jobs:
  deploy_code_to_vps:
    runs-on: ubuntu-latest
    steps:
        - name: Run Deployment Ansible Playbook
          uses: dawidd6/action-ansible-playbook@v2
          with:
            playbook: /home/runner/invoices/ansible/deploy.yaml
            directory: ./
            # SSH Private Key
            key: ${{ secrets.LIGHTSAIL_VM_SSH_KEY }}
                
