name: Deploy

on:
  push:
    branches: [develop]

jobs:
  deploy_code_to_vps:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up SSH key
          run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.LIGHTSAIL_VM_SSH_KEY }}" > ~/.ssh/ed_25519
            chmod 600 ~/.ssh/ed_25519
            ssh-keyscan -t rsa ${{ secrets.LIGHTSAIL_VM_IP }} >> ~/.ssh/known_hosts
            echo ~/.ssh/ed_25519.pub
        
        - name: Deploy using Ansible
          run: |
            ansible-playbook -i ansible/hosts --private-key ~/.ssh/ed_25519 -u optimus  ansible/deploy.yaml --verbose
